
name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: 8588e6d5d5354f52df48bbcced0d592d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}